#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER allinone WITH PASSWORD '${APP_DB_PASSWORD}';
    GRANT CONNECT ON DATABASE allinone TO allinone;
    GRANT USAGE ON SCHEMA public TO allinone;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO allinone;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO allinone;
EOSQL